// The MIT License (MIT)

// Copyright (c) 2013 lailongwei<lailongwei@126.com>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of 
// this software and associated documentation files (the "Software"), to deal in 
// the Software without restriction, including without limitation the rights to 
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of 
// the Software, and to permit persons to whom the Software is furnished to do so, 
// subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all 
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS 
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

//!!! This file is auto generated by script tool, do not modify it!!!

#ifndef __LULLBC_AUTOGEN_SRC__LULLBCMETHODS_H__
#define __LULLBC_AUTOGEN_SRC__LULLBCMETHODS_H__

#include "lullbc/common/LibHeader.h"
#include "lullbc/common/Macro.h"
#include "src/_Lullbc.h"
#include "src/common/_Config.h"
#include "src/common/_MonkeyPatch.h"
#include "src/common/_VerInfo.h"
#include "src/core/file/_Dir.h"
#include "src/core/helper/_GUIDHelper.h"
#include "src/core/log/_Log.h"
#include "src/core/thread/_Thread.h"
#include "src/core/timer/_Timer.h"
#include "src/core/timer/_TimerScheduler.h"
#include "src/core/utils/_Util_CPUTime.h"
#include "src/core/utils/_Util_Misc.h"
#include "src/core/utils/_Util_String.h"
#include "src/core/utils/_Util_Table.h"

static luaL_Reg lullbc_NativeMethods[] = {
    {"InitLog", _lullbc_InitLog},
    {"Util_Misc_ToPointer", _lullbc_Util_Misc_ToPointer},
    {"CPUTimeToUniversalTime", _lullbc_Util_CPUTimeToUniversalTime},
    {"GetVersionInfo", _lullbc_GetVersionInfo},
    {"Timer_GetPeriod", _lullbc_Timer_GetPeriod},
    {"Cleanup", _lullbc_Cleanup},
    {"Dir_Remove", _lullbc_Dir_Remove},
    {"LogMsg", _lullbc_LogMsg},
    {"Timer_GetDueTime", _lullbc_Timer_GetDueTime},
    {"Timer_GetTimerId", _lullbc_Timer_GetTimerId},
    {"MonkeyPatch", _lullbc_MonkeyPatch},
    {"Dir_AbsPath", _lullbc_Dir_AbsPath},
    {"Dir_Create", _lullbc_Dir_Create},
    {"Util_String_HashString", _lullbc_Util_String_HashString},
    {"CPUTime", _lullbc_Util_CPUTime},
    {"TimerScheduler_Update", _lullbc_TimerScheduler_Update},
    {"TimerScheduler_SetEnabled", _lullbc_TimerScheduler_SetEnabled},
    {"TimerScheduler_IsEnabled", _lullbc_TimerScheduler_IsEnabled},
    {"Dir_IsDir", _lullbc_Dir_IsDir},
    {"Timer_IsScheduling", _lullbc_Timer_IsScheduling},
    {"GetLogLevel", _lullbc_GetLogLevel},
    {"TimerScheduler_SetTimerErrorHandler", _lullbc_TimerScheduler_SetTimerErrorHandler},
    {"Startup", _lullbc_Startup},
    {"Util_Table_Concat", _lullbc_Util_Table_Concat},
    {"SetLibConfigToLua", _lullbc_SetLibConfigToLua},
    {"TimerScheduler_GetTimerCount", _lullbc_TimerScheduler_GetTimerCount},
    {"Timer_New", _lullbc_Timer_New},
    {"GUID_Generate", _lullbc_GUID_Generate},
    {"Dir_Join", _lullbc_Dir_Join},
    {"IsLogInit", _lullbc_IsLogInit},
    {"Thread_Sleep", _lullbc_Thread_Sleep},
    {"Timer_Schedule", _lullbc_Timer_Schedule},
    {NULL, NULL}
};
#endif // !__LULLBC_AUTOGEN_SRC__LULLBCMETHODS_H__

