name: MacOS build

on:
  push:
    paths-ignore:
      - ".github/workflows/linux-build.yml"
      - ".github/workflows/windows-build.yml"
      - "static/**"
      - "README.md"
      - "LICENSE"
      - "CHANGELOG"
  pull_request: {}

jobs:
  macos-build:
    name: MacOS build job
    runs-on: macOS-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Compile core library(Debug and Release)
        run: |
          make llbc config=Debug verbose=1 -j4
          make llbc config=Release verbose=1 -j4

      - name: Compile tests targets(Debug and Release)
        run: |
          make tests config=Debug verbose=1 -j4
          make tests config=Release verbose=1 -j4

      - name: Compile pyllbc wrap library(Debug and Release)
        run: |
          make pyllbc config=Debug verbose=1 -j4
          make pyllbc config=Release verbose=1 -j4

      - name: Compile lullbc wrap library(Debug and Release)
        run: |
          make lullbc config=Debug verbose=1 -j4
          make lullbc config=Release verbose=1 -j4
        
      - run: echo "🍏 This job's status is ${{ job.status }}."
