name: Windows build

on:
  push:
    paths-ignore:
      - ".github/workflows/linux-build.yml"
      - ".github/workflows/macos-build.yml"
      - "static/**"
      - "README.md"
      - "LICENSE"
      - "CHANGELOG"
  pull_request: {}

jobs:
  windows-build:
    name: Windows build (${{ matrix.os }} / ${{ matrix.vs_version }}, ${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: windows-2022, vs_version: 'vs2022', configuration: Debug }
          - { os: windows-2022, vs_version: 'vs2022', configuration: Release }
          - { os: windows-2022, vs_version: 'vs2022', configuration: MinSizeRel }
          - { os: windows-2022, vs_version: 'vs2022', configuration: RelWithDebInfo }
          - { os: windows-2025, vs_version: 'vs2026', configuration: Debug }
          - { os: windows-2025, vs_version: 'vs2026', configuration: Release }
          - { os: windows-2025, vs_version: 'vs2026', configuration: MinSizeRel }
          - { os: windows-2025, vs_version: 'vs2026', configuration: RelWithDebInfo }
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      
      - name: Setup Visual Studio and MSBuild environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
        
      - name: PreBuild
        run: echo ${{ matrix.vs_version }} | ./WinPreBuild.bat 0

      - name: Compile llbc core lib
        run: cmake --build build_${{ matrix.vs_version }} --config ${{ matrix.configuration }} --target llbc_shared llbc_static

      - name: Compile example
        run: cmake --build build_${{ matrix.vs_version }} --config ${{ matrix.configuration }} --target example_shared example_static

      - name: Compile func_test
        run: cmake --build build_${{ matrix.vs_version }} --config ${{ matrix.configuration }} --target func_test_shared func_test_static

      - name: Compile unit_test
        run: cmake --build build_${{ matrix.vs_version }} --config ${{ matrix.configuration }} --target unit_test_shared unit_test_static

      - name: Compile python wrap library
        run: cmake --build build_${{ matrix.vs_version }} --config ${{ matrix.configuration }} --target pyllbc

      - name: Compile lua wrap library
        run: cmake --build build_${{ matrix.vs_version }} --config ${{ matrix.configuration }} --target lullbc

      - name: Compile c# wrap library
        run: cmake --build build_${{ matrix.vs_version }} --config ${{ matrix.configuration }} --target csllbc_testsuite

      - run: echo "🍏 This job's status is ${{ job.status }}."
