name: Windows build

on:
  push:
    paths-ignore:
      - ".github/workflows/linux-build.yml"
      - ".github/workflows/macos-build.yml"
      - "static/**"
      - "README.md"
      - "LICENSE"
      - "CHANGELOG"
  pull_request: {}

jobs:
  windows-build:
    name: Windows build job
    runs-on: windows-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      
      - name: Setup Visual Studio and MSBuild environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
        
      - name: PreBuild
        run: echo vs2022 | ./WinPreBuild.bat 0
        
      - name: Compile llbc core lib
        run: |
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Debug -p:Platform=x64 -t:llbc_shared;llbc_static
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Release -p:Platform=x64 -t:llbc_shared;llbc_static
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=MinSizeRel -p:Platform=x64 -t:llbc_shared;llbc_static
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=RelWithDebInfo -p:Platform=x64 -t:llbc_shared;llbc_static
        
      - name: Compile example
        run: |
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Debug -p:Platform=x64 -t:example_shared;example_static
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Release -p:Platform=x64 -t:example_shared;example_static
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=MinSizeRel -p:Platform=x64 -t:example_shared;example_static
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=RelWithDebInfo -p:Platform=x64 -t:example_shared;example_static

      - name: Compile func_test
        run: |
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Debug -p:Platform=x64 -t:func_test_shared;func_test_static
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Release -p:Platform=x64 -t:func_test_shared;func_test_static
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=MinSizeRel -p:Platform=x64 -t:func_test_shared;func_test_static
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=RelWithDebInfo -p:Platform=x64 -t:func_test_shared;func_test_static

      - name: Compile unit_test
        run: |
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Debug -p:Platform=x64 -t:unit_test_shared;unit_test_static
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Release -p:Platform=x64 -t:unit_test_shared;unit_test_static
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=MinSizeRel -p:Platform=x64 -t:unit_test_shared;unit_test_static
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=RelWithDebInfo -p:Platform=x64 -t:unit_test_shared;unit_test_static

      - name: Compile python wrap library
        run: |
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Debug -p:Platform=x64 -t:pyllbc
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Release -p:Platform=x64 -t:pyllbc
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=MinSizeRel -p:Platform=x64 -t:pyllbc
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=RelWithDebInfo -p:Platform=x64 -t:pyllbc

      - name: Compile lua wrap library
        run: |
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Debug -p:Platform=x64 -t:lullbc
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Release -p:Platform=x64 -t:lullbc
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=MinSizeRel -p:Platform=x64 -t:lullbc
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=RelWithDebInfo -p:Platform=x64 -t:lullbc

      - name: Compile c# wrap library
        run: |
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Debug -p:Platform=x64 -t:csllbc_testsuite
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=Release -p:Platform=x64 -t:csllbc_testsuite
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=MinSizeRel -p:Platform=x64 -t:csllbc_testsuite
          msbuild.exe build_vs2022/llbc.sln -p:Configuration=RelWithDebInfo -p:Platform=x64 -t:csllbc_testsuite

      - run: echo "🍏 This job's status is ${{ job.status }}."
